name: Daily Weather to Slack

on:
  schedule:
    # 매일 0시 UTC → 한국시각 9시
    - cron: '0 0 * * *'
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  post-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: Python 세팅
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 날씨 정보 슬랙으로 전송
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: python weather_post.py
